config/routes.rb
Rails.application.routes.draw do
  get 'homes/about'
  get 'homes/top'
  root 'homes#top'
  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :registrations => "users/registrations"
  }
  devise_for :admins, :controllers => {
    :sessions => "admins/sessions"
  }
  resources :users, only: [:create,:show,:edit, :update, :destroy] do
    resources :comments,only: [:create, :destroy]
    resource :favorites,only: [:create, :destroy]
  end

  post 'bikes' => 'bikes#create'
  get 'bikes' => 'bikes#index'
  get 'bikes/:id' => 'bikes#show', as: 'bike'
  get 'bikes/:id/edit' => 'bikes#edit', as: 'edit_bike'
  patch 'bikes/:id' => 'bikes#update', as: 'update_bike'
  delete 'bikes/:id' => 'bikes#destroy', as: 'destroy_bike'

  resources :comments

  post   '/favorite/:bike_id' => 'favorites#favorite',   as: 'favorite'
  delete '/favorite/:bike_id' => 'favorites#unfavorite', as: 'unfavorite'

  resources :follows, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bikes, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :profile_image
  has_many :favorites, dependent: :destroy
  has_many :favorite_bikes, through: :favorites, source: :favorite
  has_many :followed_follows, foreign_key: "follower_id", class_name: "Follow",  dependent: :destroy
  has_many :followed, through: :followed_follows
  validates :name, presence: true

	def followed?(user)
		followed_follows.find_by(followed_id: user.id)
	end

	def follow(user)
		followed_follows.create!(followed_id: user.id)
	end

	def unfollow(user)
		followed_follows.find_by(followed_id: user.id).destroy
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :colect_user, only: [:edit, :update]

  def index
  end

  def show
    @user = User.find(params[:id])
    @bike = Bike.new
    @bikes = @user.bikes
    @favorites = @user.favorites
    @follows = @user.followed_follows
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def destroy
  end

  private
  def user_params
      params.require(:user).permit(:name, :profile_image)
  end
  def colect_user
   @user = User.find(params[:id])
     if @user.id != current_user.id
        redirect_to bikes_path(current_user)
     end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.followed_follows.build, remote: true) do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit "フォローする",class: "btn btn-primary btn-sm" %>
  <%= Follow.where(followed_id: params[:followed_id]).size %>
<% end %>

app/views/users/_follow_form.html.erb
<% if user_signed_in? && @user != current_user %>
  <div id="follow_form">
    <% if current_user.followed?(@user) %>
      <%= render "unfollow" %>
    <% else %>
      <span id="a"><%= render "follow" %></span>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.followed_follows.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
	<%= f.submit "フォロー解除",class: "btn btn-primary btn-sm" %>
	<%= Follow.where(followed_id: params[:followed_id]).size %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
<div class="row">
<div class="col-12">
	<h1>プロフィール編集</h1>
	<%= form_for(@user) do |f| %>
	<lavel>名前</lavel>
	<%= f.text_field :name %></br>
	<%= attachment_image_tag @user, :profile_image, :fill, 90, 100, fallback: "no_image.jpg"%>
	<%= f.attachment_field :profile_image %>
	<%= f.submit "変更を保存" %>
	<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="sageru">
	<div class="container">
		<div class="row">
			<div class="col-3">
				<h2>プロフィール</h2>
				<%= attachment_image_tag @user, :profile_image, :fill, 100, 100,  fallback: "no_image.jpg" %><br>
						<%= @user.name %><br>

				<%= render "follow_form" %>

				<% if current_user == @user %>
					<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
					プロフィール編集
					</button>
					<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title" id="exampleModalLabel">プロフィール編集</h5>
									<button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
									<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<%= form_for(@user) do |f| %>
								<div class="modal-body">
									<%= attachment_image_tag @user, :profile_image, :fill, 90, 100, fallback: "no_image.jpg"%>
									<%= f.attachment_field :profile_image %><br>
									<lavel>名前</lavel>
									<%= f.text_field :name %>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
									<%= f.submit "変更を保存",class: "btn btn-info" %>
								</div>
								<% end %>
							</div>
						</div>
					</div>
				<% end %>
			</div>

			<div class="col-9 post-favorite">

				<tab>
				<a href="javascript:void(0);" data-tab="one" class="active">投稿一覧</a>
				<a href="javascript:void(0);" data-tab="two" clsas="active">いいね一覧</a>
				<a href="javascript:void(0);" data-tab="three">フォロー一覧</a>
				<div class="clear"></div>
				</tab>

				<div class="tabContainer">
					<div id="one" class="Tabcondent active">
						<% @bikes.each do |bike| %>
							<div class="box">
								<%= attachment_image_tag bike.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %>
								<%= bike.user.name %><br>
								<%= link_to bike.text,bike_path(bike.id) %><br>
								<div class="row mypagetoukou">
									<% bike.bike_images.each do |bike_image| %>
										<div class="col-6">
											<%= attachment_image_tag bike_image, :image, :fill, 250, 250, format: 'jpeg' %><br>
										</div>
									<% end %>
								</div>
								<%= bike.created_at.strftime('%Y/%m/%d/%H:%M') %><br>
								<div class="row">
									<div class="col-3">
										<%= link_to "#{bike.comments.count} コメント", bike_path(bike.id) %>
									</div>
									<div class="col-3">
										<%= render  'bikes/bikes', bike: bike %>
									</div>
								</div>
							</div>
						<% end %>
					</div>

					<div id="two" class="Tabcondent">
						<% @favorites.each do |favorite| %>
							<div class="box">
								<%= link_to user_path(favorite.bike.user) do %>
									<%= attachment_image_tag favorite.bike.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %>
								<% end %>
								<%= favorite.bike.user.name %><br>
								<%= link_to favorite.bike.text,bike_path(favorite.bike.id) %><br>
								<div class="row mypagetoukou">
									<% favorite.bike.bike_images.each do |bike_image| %>
										<div class="col-6">
											<%= attachment_image_tag bike_image, :image, :fill, 250, 250, format: 'jpeg' %><br>
										</div>
									<% end %>
								</div>
								<%= favorite.bike.created_at.strftime('%Y/%m/%d/%H:%M') %><br>
								<div class="row">
									<div class="col-3">
										<%= link_to "#{favorite.bike.comments.count} コメント", bike_path(favorite.bike.id) %>
									</div>
									<div class="col-3">
										<%= render  'bikes/bikes', bike: favorite.bike %>
									</div>
								</div>
							</div>
						<% end %>
					</div>

					<div id="three" class="Tabcondent">
						<% @user.followed_follows.each do |f| %>
						  <% follow = User.find_by(id: f.followed_id) %>
							<table>
								<th>
								<%= link_to user_path(follow) do %>
								<%= attachment_image_tag follow, :profile_image, :fill, 70, 70,  fallback: "no_image.jpg" %>
								<% end %>
							</th>
								<td><%= follow.name %></td>
							</table>
						<% end %>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>