config/routes.rb
Rails.application.routes.draw do
  get 'homes/about'
  get 'homes/top'
  root 'homes#top'
  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :registrations => "users/registrations"
  }
  devise_for :admins, :controllers => {
    :sessions => "admins/sessions"
  }
  resources :users, only: [:create,:show,:edit, :update, :destroy] do
    resources :comments,only: [:create, :destroy]
    resource :favorites,only: [:create, :destroy]
  end

  post 'bikes' => 'bikes#create'
  get 'bikes' => 'bikes#index'
  get 'bikes/:id' => 'bikes#show', as: 'bike'
  get 'bikes/:id/edit' => 'bikes#edit', as: 'edit_bike'
  patch 'bikes/:id' => 'bikes#update', as: 'update_bike'
  delete 'bikes/:id' => 'bikes#destroy', as: 'destroy_bike'

  resources :comments

  post   '/favorite/:bike_id' => 'favorites#favorite',   as: 'favorite'
  delete '/favorite/:bike_id' => 'favorites#unfavorite', as: 'unfavorite'

  resources :follows, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
    has_many :favoriting_users, through: :favorites, source: :user
    has_many :bike_images
    accepts_attachments_for :bike_images, attachment: :image
    validates :text, presence: true
    validates :text, length: {maximum: 140}
    default_scope -> { order(created_at: :desc) }
end

app/models/bike_image.rb
class BikeImage < ApplicationRecord
	belongs_to :bike
	attachment :image
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :bike
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :bike, counter_cache: :favorites_count
    belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bikes, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :profile_image
  has_many :favorites, dependent: :destroy
  has_many :favorite_bikes, through: :favorites, source: :favorite
  has_many :followed_follows, foreign_key: "follower_id", class_name: "Follow",  dependent: :destroy
  has_many :followed, through: :followed_follows
  validates :name, presence: true

	def followed?(user)
		followed_follows.find_by(followed_id: user.id)
	end

	def follow(user)
		followed_follows.create!(followed_id: user.id)
	end

	def unfollow(user)
		followed_follows.find_by(followed_id: user.id).destroy
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		bikes_path
    end
    def after_sign_up_path_for(resource)
    	bikes_path
    end
	protected
		def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile_image])
		end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :setbike, only: [:edit, :update, :destroy]
  before_action :colect_user, only:[:edit, :update]

  def index
    @bike = Bike.new
    @q = Bike.ransack(params[:q])
    @bikes = @q.result(distinct: true)
  end

  def search
    @q = Bike.search(search_params)
    @bikes = @q.result(distinct: true)
  end

  def show
    @bike = Bike.find(params[:id])
    @bike_comment = Comment.new
  end

  def create
    @bike = current_user.bikes.build(bike_params)
    @bike.save
    redirect_to bikes_path
  end

  def edit
  end

  def update
    @bike.update(bike_params)
    redirect_to bike_path(@bike.id)
  end

  def destroy
    @bike.destroy
    redirect_to bikes_path
  end
  private
  def bike_params
    params.require(:bike).permit(:text,:user_id, :video, bike_images_images: [])
  end
  def setbike
    @bike = current_user.bikes.find(params[:id])
  end
  def search_params
    params.require(:q).permit!
  end
  def colect_user
     @bike = Bike.find(params[:id])
     if @bike.user_id != current_user.id
        redirect_to bikes_path
   end
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	    comment = current_user.comments.new(comment_params)
	    comment.save
	    redirect_to bike_path(comment.bike_id)
	end
end
private
def comment_params
    params.require(:comment).permit(:user_id,:bike_id,:text)
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	 before_action :set_favorites

  def favorite
    favorite = current_user.favorites.new(bike_id: @bike.id)
    favorite.save
  end

  def unfavorite
    favorite = current_user.favorites.find_by(bike_id: @bike.id)
    favorite.destroy
  end

  private

  def set_favorites
    @bike = Bike.find(params[:bike_id])
    @id_name = "#favorite-link-#{@bike.id}"
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
	def create
		@user = User.find(params[:followed_id])
		current_user.follow(@user)
	end

	def destroy
		@user = Follow.find(params[:id]).followed
		current_user.unfollow(@user)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end

  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :colect_user, only: [:edit, :update]

  def index
  end

  def show
    @user = User.find(params[:id])
    @bike = Bike.new
    @bikes = @user.bikes
    @favorites = @user.favorites
    @follows = @user.followed_follows
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def destroy
  end

  private
  def user_params
      params.require(:user).permit(:name, :profile_image)
  end
  def colect_user
   @user = User.find(params[:id])
     if @user.id != current_user.id
        redirect_to bikes_path(current_user)
     end
  end
end

app/helpers/admin/managers_helper.rb
module Admin::ManagersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bikes/_bikes.html.erb
<%= render 'favorites/favorite', bike: bike %>

app/views/bikes/edit.html.erb
			<% if current_user == @user %>
				<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
				プロフィール編集
				</button>
				<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
					<div class="modal-dialog" role="document">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title" id="exampleModalLabel">プロフィール編集</h5>
								<button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
								<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<%= form_for(@bike) do |f| %>
							<div class="modal-body">
								<%= f.text_area :text %>
								<%= attachment_image_tag @bike, :image, :fill, 300, 300, format: 'jpeg' %>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
								<%= f.submit '変更',class: "btn btn-info" %>
							</div>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>

app/views/bikes/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-2">
		</div>
			<div class="col-8">
				<h2>投稿一覧</h2>

				<%= search_form_for @q  do |f| %>
					<div class="row">
						<div class="col-9">
							<div class="form-group"><%= f.text_field :text_cont, class: "form-control" %></div>
						</div>
						<div class="col3 search-action">
							<div class="fas fa-search"><%= f.submit "検索" %></div>
						</div>
					</div>
				<% end %>

				<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
				投稿
				</button>
				<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
					<div class="modal-dialog" role="document">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title" id="exampleModalLabel">Bikers</h5>
								<button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
								<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<%= form_for @bike do |f| %>
								<div class="modal-body">
									<h4>本文</h4>
									<%= f.text_area :text %>
									<h4>画像</h4>
									<%= f.attachment_field :bike_images_images, multiple: true %>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
									<%= f.submit '投稿',class: "btn btn-info" %>
								</div>
							<% end %>
						</div>
					</div>
				</div>

				<% @bikes.each do |bike| %>
				<div class="box">
					<%= link_to user_path(bike.user) do %>
			   			<%= attachment_image_tag bike.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %>
			   		<% end %>
				    <%= bike.user.name %><br>
					<%= link_to bike.text,bike_path(bike.id) %><br>
					<div class="row mypagetoukou">
						<% bike.bike_images.each do |bike_image| %>
						<div class="col-6">
							<%= attachment_image_tag bike_image, :image, :fill, 250, 250, format: 'jpeg' %><br>
						</div>
						<% end %>
					</div>


					<%= bike.created_at.strftime("%Y/%m/%d/%H:%M") %><br>
				    <div class="row">
				    	<div class="col-3 favorite">
				   		 <%= link_to "#{bike.comments.count} コメント", bike_path(bike.id) %>
				        </div>
				        <div class="col-3">
				  		  <%= render  'bikes/bikes', bike: bike %>
				        </div>
			    	</div>
				</div>
				<% end %>
			</div>
	</div>
</div>

app/views/bikes/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-2">
		</div>
		<div class="col-8">
			<h2>投稿詳細</h2>
			<div class="box">
				<% if current_user == @bike.user %>
					<%= link_to "削除", destroy_bike_path(@bike.id),class: "fas fa-trash-alt",method: :delete, "data-confirm" => "本当に削除しますか？" %>
					<button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#exampleModal">
					編集
					</button>
					<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title" id="exampleModalLabel">編集</h5>
									<button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
									<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<%= form_for(@bike) do |f| %>
								<div class="modal-body">
									<%= f.text_area :text %>
									<%= attachment_image_tag @bike, :image, :fill, 300, 300, format: 'jpeg' %>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
									<%= f.submit '変更',class: "btn btn-info" %>
								</div>
								<% end %>
							</div>
						</div>
					</div>

				<% end %>
				<%= link_to user_path(@bike.user) do %>
					<%= attachment_image_tag @bike.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %>
				<% end %>
				<%= @bike.user.name %><br>
				<%= @bike.text %><br>

				<div class="row mypagetoukou">
					<% @bike.bike_images.each do |bike_image| %>
					<div class="col-6">
						<%= attachment_image_tag bike_image, :image, :fill, 250, 250, format: 'jpeg' %><br>
					</div>
					<% end %>
				</div>
				<%= @bike.created_at.strftime('%Y/%m/%d/%H:%M') %><br>

				<div class="row">
					<div class="col-3">
						<%= @bike.comments.count %>件コメント
				    </div>
				    <div class="col-3">
				    	<%= render  'bikes/bikes', bike: @bike %>
					</div>
				</div>
				<% @bike.comments.each do |comment| %>
					<%= link_to user_path(@bike.user) do %>
					<%= attachment_image_tag comment.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %>
					<% end %>
					<%= comment.user.name %><br>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= comment.text %><br>
					<%= comment.created_at.strftime('%Y/%m/%d/%H:%M') %><br>
				<% end %>

				<%= form_for(@bike_comment) do |f| %>
					<%= f.hidden_field :bike_id, :value => @bike.id %>
					<%= f.text_area :text,placeholder: "コメントをここに" %>
					<%= f.submit "送信する" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/favorites/_favorite.html.erb
<div class="favorite-link" id="favorite-link-<%= bike.id %>">
  <% if current_user.favorites.find_by(bike_id: bike.id) %>
    <%= link_to unfavorite_path(bike.id), method: :delete, remote: true do %>
        <div class = "iine__button">いいね❤️<%= bike.favorites.count %></div>
    <% end %>
  <% else %>
    <%= link_to favorite_path(bike.id), method: :post, remote: true do %>
        <div class = "iine__button">いいね♡️<%= bike.favorites.count %></div>
    <% end %>
  <% end %>
</div>

app/views/favorites/favorite.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("favorites/favorite", bike: @bike  )) %>');

app/views/favorites/unfavorite.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("favorites/favorite", bike: @bike  )) %>');

app/views/follows/create.js.erb
$("#follow_form").html("<%= j(render 'users/unfollow') %>");

app/views/follows/destroy.js.erb
$("#follow_form").html("<%= j(render'users/follow') %>");