config/routes.rb
Rails.application.routes.draw do
  get 'homes/about'
  get 'homes/top'
  root 'homes#top'
  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :registrations => "users/registrations"
  }
  devise_for :admins, :controllers => {
    :sessions => "admins/sessions"
  }
  resources :users, only: [:create,:show,:edit, :update, :destroy] do
    resources :comments,only: [:create, :destroy]
    resource :favorites,only: [:create, :destroy]
  end

  post 'bikes' => 'bikes#create'
  get 'bikes' => 'bikes#index'
  get 'bikes/:id' => 'bikes#show', as: 'bike'
  get 'bikes/:id/edit' => 'bikes#edit', as: 'edit_bike'
  patch 'bikes/:id' => 'bikes#update', as: 'update_bike'
  delete 'bikes/:id' => 'bikes#destroy', as: 'destroy_bike'

  resources :comments

  post   '/favorite/:bike_id' => 'favorites#favorite',   as: 'favorite'
  delete '/favorite/:bike_id' => 'favorites#unfavorite', as: 'unfavorite'

  resources :follows, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
    has_many :favoriting_users, through: :favorites, source: :user
    has_many :bike_images
    accepts_attachments_for :bike_images, attachment: :image
    validates :text, presence: true
    validates :text, length: {maximum: 140}
    default_scope -> { order(created_at: :desc) }
end

app/models/bike_image.rb
class BikeImage < ApplicationRecord
	belongs_to :bike
	attachment :image
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :bike
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :bike, counter_cache: :favorites_count
    belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bikes, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :profile_image
  has_many :favorites, dependent: :destroy
  has_many :favorite_bikes, through: :favorites, source: :favorite
  has_many :followed_follows, foreign_key: "follower_id", class_name: "Follow",  dependent: :destroy
  has_many :followed, through: :followed_follows
  validates :name, presence: true

	def followed?(user)
		followed_follows.find_by(followed_id: user.id)
	end

	def follow(user)
		followed_follows.create!(followed_id: user.id)
	end

	def unfollow(user)
		followed_follows.find_by(followed_id: user.id).destroy
	end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :setbike, only: [:edit, :update, :destroy]
  before_action :colect_user, only:[:edit, :update]

  def index
    @bike = Bike.new
    @q = Bike.ransack(params[:q])
    @bikes = @q.result(distinct: true)
  end

  def search
    @q = Bike.search(search_params)
    @bikes = @q.result(distinct: true)
  end

  def show
    @bike = Bike.find(params[:id])
    @bike_comment = Comment.new
  end

  def create
    @bike = current_user.bikes.build(bike_params)
    @bike.save
    redirect_to bikes_path
  end

  def edit
  end

  def update
    @bike.update(bike_params)
    redirect_to bike_path(@bike.id)
  end

  def destroy
    @bike.destroy
    redirect_to bikes_path
  end
  private
  def bike_params
    params.require(:bike).permit(:text,:user_id, :video, bike_images_images: [])
  end
  def setbike
    @bike = current_user.bikes.find(params[:id])
  end
  def search_params
    params.require(:q).permit!
  end
  def colect_user
     @bike = Bike.find(params[:id])
     if @bike.user_id != current_user.id
        redirect_to bikes_path
   end
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	    comment = current_user.comments.new(comment_params)
	    comment.save
	    redirect_to bike_path(comment.bike_id)
	end
end
private
def comment_params
    params.require(:comment).permit(:user_id,:bike_id,:text)
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
	def create
		@user = User.find(params[:followed_id])
		current_user.follow(@user)
	end

	def destroy
		@user = Follow.find(params[:id]).followed
		current_user.unfollow(@user)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end

  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :colect_user, only: [:edit, :update]

  def index
  end

  def show
    @user = User.find(params[:id])
    @bike = Bike.new
    @bikes = @user.bikes
    @favorites = @user.favorites
    @follows = @user.followed_follows
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def destroy
  end

  private
  def user_params
      params.require(:user).permit(:name, :profile_image)
  end
  def colect_user
   @user = User.find(params[:id])
     if @user.id != current_user.id
        redirect_to bikes_path(current_user)
     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
    <!DOCTYPE html>
    <html>
      <head>
        <title>Bikers</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
      </head>

      <body>
<div class="wrapper">
<header>
  <% if user_signed_in? %>
  <div class="fas fa-motorcycle">Bikers</div>

    <div class="menu-trigger" href="">
      <span></span>
      <span></span>
      <span></span>
    </div>

    <nav>
      <ul>
        <li> <%= link_to '投稿一覧', bikes_path, class: "fas fa-motorcycle" %> </li>
        <li> <%= link_to 'マイページ',user_path(current_user.id), class: "fas fa-user" %></li>
        <li> <%= link_to 'ログアウト',destroy_user_session_path,method: :delete, class: "fas fa-sign-out-alt" %></li>
       </ul>
    </nav>
    <div class="overlay"></div>

  <% else %>

  <div class="menu-trigger" href="">
      <span></span>
      <span></span>
      <span></span>
  </div>

  <div class="fas fa-motorcycle">Bikers</div>
  <nav>
    <ul>
      <li><%= link_to 'ホーム', root_path,class: "fas fa-home" %> </li>
      <li> <%= link_to 'アバウト',homes_about_path,class: "fas fa-hands-helping" %> </li>
      <li>  <%= link_to '新規登録',new_user_registration_path,class: "fas fa-user-plus" %></li>
      <li> <%= link_to 'ログイン',new_user_session_path,class: "fas fa-sign-in-alt" %></li>
    </ul>
  </nav>
  <div class="overlay"></div>

  <% end %>
</header>
</div>

    <%= yield %>
      </body>
    </html>